/* 
VISTAS:
lAS PODEMOS DEFINIR COMO UNA CONSULTA ALMACENADA EN LA BASE DE DATOS 
QUE SE UTILIZA COMO UNA TABAL VIRTUAL Y NO ALMACENA DATOS SI NO QUE 
UTILIZA ASOCIACIONES Y LOS DATOS DE LAS TABLAS ORIGINALES DE FORMA 
QUE SIEMPRE SE MANTIENEN ACTUALIZADAS 
 */

CREATE VIEW entradas_con_nombres AS 
SELECT e.id, e.titulo, u.nombre AS 'Autor', c.nombre AS 'Categoria'
FROM entradas e
INNER JOIN usuarios u ON e.usuario_id = u.id
INNER JOIN categorias c ON e.categoria_id = c.id;

